# Generated by Django 4.2.3 on 2023-09-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='allUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.TextField()),
            ],
        ),
    ]
