# Generated by Django 3.2.20 on 2024-02-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_allurls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allurls',
            name='urls',
        ),
        migrations.AddField(
            model_name='allurls',
            name='shortenUrl',
            field=models.CharField(default='https://google.com', max_length=100),
        ),
        migrations.AddField(
            model_name='allurls',
            name='userUrl',
            field=models.CharField(default='https://google.com', max_length=100),
            preserve_default=False,
        ),
    ]
